# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.30.3/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.30.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/dadidou/Documents/Telecom/1A/Info/Compilation/Imperative_Compiler/Interpreter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/dadidou/Documents/Telecom/1A/Info/Compilation/Imperative_Compiler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.30.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.30.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dadidou/Documents/Telecom/1A/Info/Compilation/Imperative_Compiler/CMakeFiles /Users/dadidou/Documents/Telecom/1A/Info/Compilation/Imperative_Compiler//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dadidou/Documents/Telecom/1A/Info/Compilation/Imperative_Compiler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /Users/dadidou/Documents/Telecom/1A/Info/Compilation/Imperative_Compiler/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Interpreter

# Build rule for target.
Interpreter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Interpreter
.PHONY : Interpreter

# fast build rule for target.
Interpreter/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/build
.PHONY : Interpreter/fast

interpreter.o: interpreter.cpp.o
.PHONY : interpreter.o

# target to build an object file
interpreter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/interpreter.cpp.o
.PHONY : interpreter.cpp.o

interpreter.i: interpreter.cpp.i
.PHONY : interpreter.i

# target to preprocess a source file
interpreter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/interpreter.cpp.i
.PHONY : interpreter.cpp.i

interpreter.s: interpreter.cpp.s
.PHONY : interpreter.s

# target to generate assembly for a file
interpreter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/interpreter.cpp.s
.PHONY : interpreter.cpp.s

json_reader.o: json_reader.cpp.o
.PHONY : json_reader.o

# target to build an object file
json_reader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/json_reader.cpp.o
.PHONY : json_reader.cpp.o

json_reader.i: json_reader.cpp.i
.PHONY : json_reader.i

# target to preprocess a source file
json_reader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/json_reader.cpp.i
.PHONY : json_reader.cpp.i

json_reader.s: json_reader.cpp.s
.PHONY : json_reader.s

# target to generate assembly for a file
json_reader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/json_reader.cpp.s
.PHONY : json_reader.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/main.cpp.s
.PHONY : main.cpp.s

token.o: token.cpp.o
.PHONY : token.o

# target to build an object file
token.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/token.cpp.o
.PHONY : token.cpp.o

token.i: token.cpp.i
.PHONY : token.i

# target to preprocess a source file
token.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/token.cpp.i
.PHONY : token.cpp.i

token.s: token.cpp.s
.PHONY : token.s

# target to generate assembly for a file
token.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/token.cpp.s
.PHONY : token.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Interpreter"
	@echo "... interpreter.o"
	@echo "... interpreter.i"
	@echo "... interpreter.s"
	@echo "... json_reader.o"
	@echo "... json_reader.i"
	@echo "... json_reader.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... token.o"
	@echo "... token.i"
	@echo "... token.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /Users/dadidou/Documents/Telecom/1A/Info/Compilation/Imperative_Compiler/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

